export const PAISES_NACIMIENTO = [
  { codigo: '57',  bandera: '🇨🇴', nombre: 'Colombia'         },
  { codigo: '52',  bandera: '🇲🇽', nombre: 'México'           },
  { codigo: '54',  bandera: '🇦🇷', nombre: 'Argentina'        },
  { codigo: '51',  bandera: '🇵🇪', nombre: 'Perú'             },
  { codigo: '56',  bandera: '🇨🇱', nombre: 'Chile'            },
  { codigo: '593', bandera: '🇪🇨', nombre: 'Ecuador'          },
  { codigo: '58',  bandera: '🇻🇪', nombre: 'Venezuela'        },
  { codigo: '595', bandera: '🇵🇾', nombre: 'Paraguay'         },
  { codigo: '598', bandera: '🇺🇾', nombre: 'Uruguay'          },
  { codigo: '591', bandera: '🇧🇴', nombre: 'Bolivia'          },
  { codigo: '506', bandera: '🇨🇷', nombre: 'Costa Rica'       },
  { codigo: '502', bandera: '🇬🇹', nombre: 'Guatemala'        },
  { codigo: '503', bandera: '🇸🇻', nombre: 'El Salvador'      },
  { codigo: '504', bandera: '🇭🇳', nombre: 'Honduras'         },
  { codigo: '505', bandera: '🇳🇮', nombre: 'Nicaragua'        },
  { codigo: '507', bandera: '🇵🇦', nombre: 'Panamá'           },
  { codigo: '1',   bandera: '🇩🇴', nombre: 'Rep. Dominicana'  },
  { codigo: '53',  bandera: '🇨🇺', nombre: 'Cuba'             },
  { codigo: '509', bandera: '🇭🇹', nombre: 'Haití'            },
  { codigo: '592', bandera: '🇬🇾', nombre: 'Guyana'           },
  { codigo: '597', bandera: '🇸🇷', nombre: 'Surinam'          },
  { codigo: '34',  bandera: '🇪🇸', nombre: 'España'           },
  { codigo: '351', bandera: '🇵🇹', nombre: 'Portugal'         },
  { codigo: '55',  bandera: '🇧🇷', nombre: 'Brasil'           },
  { codigo: '1',   bandera: '🇺🇸', nombre: 'Estados Unidos'   },
];
